name: edu_chat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: 3.6.0
  # Flutter plugin for Firebase Auth, enabling authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter
  firebase_auth: 5.3.1
  # Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS.
  firebase_storage: 12.3.2
  # A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
  timeago: 3.7.0
  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: 1.1.2
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: 6.1.2
  # A simple (but correct) dart class for validating email addresses
  email_validator: 3.0.0
  # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  firebase_messaging: 15.1.3
  # A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: 17.2.3
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: 2.0.10+1
  # A library designed for seamless internet connectivity checks. This library enables you to verify your internet connection.
  internet_connection_checker: 1.0.0+1
  # Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: 3.4.1
  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: 2.4.1
  # Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: 3.0.0
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: 2.0.5
  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization and offline support on Android and iOS.
  cloud_firestore: 5.4.4
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: 1.2.2
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: 0.14.1
  # A bridge package between google_sign_in and googleapis_auth, to create Authenticated Clients from google_sign_in user credentials.
  extension_google_sign_in_as_googleapis_auth: 2.0.12
  # Flutter plugin for Google Sign-In, a secure authentication system for signing in with a Google account
  google_sign_in: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Arabic.ttf