// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMS6hokEx99Kg-x799Uuv6y19W1yBgWY',
    appId: '1:252294155566:web:388d0c305cafd89b697ebf',
    messagingSenderId: '252294155566',
    projectId: 'edu-chat-36688',
    authDomain: 'edu-chat-36688.firebaseapp.com',
    storageBucket: 'edu-chat-36688.appspot.com',
    measurementId: 'G-6RKM7EKXFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIoAoKWDdehxnRUCnBkDgYGzc-uVTpUQ',
    appId: '1:252294155566:android:800daec28efb4bd7697ebf',
    messagingSenderId: '252294155566',
    projectId: 'edu-chat-36688',
    storageBucket: 'edu-chat-36688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIOUCy1a1mrFwwY2fl86xBYdEctA0W7wc',
    appId: '1:252294155566:ios:4b2266a2a198606a697ebf',
    messagingSenderId: '252294155566',
    projectId: 'edu-chat-36688',
    storageBucket: 'edu-chat-36688.appspot.com',
    iosBundleId: 'com.example.eduChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIOUCy1a1mrFwwY2fl86xBYdEctA0W7wc',
    appId: '1:252294155566:ios:4b2266a2a198606a697ebf',
    messagingSenderId: '252294155566',
    projectId: 'edu-chat-36688',
    storageBucket: 'edu-chat-36688.appspot.com',
    iosBundleId: 'com.example.eduChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDMS6hokEx99Kg-x799Uuv6y19W1yBgWY',
    appId: '1:252294155566:web:94366fd833d5a50c697ebf',
    messagingSenderId: '252294155566',
    projectId: 'edu-chat-36688',
    authDomain: 'edu-chat-36688.firebaseapp.com',
    storageBucket: 'edu-chat-36688.appspot.com',
    measurementId: 'G-Q1N97GZZSH',
  );
}
